# -*- coding: utf-8 -*-
"""counting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DXeuUeZXFhkUYe6Iu6NcJI-3-3OxuPy4
"""

score = input().split()
count = 0
for i in score:
  if int(i) < 60:
    count = count + 1
print(count)